// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeoCopilot.Infrastructure.Persistence;

#nullable disable

namespace SeoCopilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeoCopilotDbContext))]
    [Migration("20260829073025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressForm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("address_form");

                    b.PrimitiveCollection<List<string>>("BannedPhrases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("banned_phrases");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("DefaultHashtags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("default_hashtags");

                    b.Property<string>("EmojiUsage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("emoji_usage");

                    b.Property<string>("ExtraContext")
                        .HasColumnType("text")
                        .HasColumnName("extra_context");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("target_audience");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tone");

                    b.HasKey("Id")
                        .HasName("pk_brand_profiles");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_brand_profiles_site_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_brand_profiles_tenant_id");

                    b.ToTable("brand_profiles", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.ContentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_profile_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("PlatformCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform_code");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TokensIn")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_in");

                    b.Property<int>("TokensOut")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_out");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_content_jobs");

                    b.HasIndex("BrandProfileId")
                        .HasDatabaseName("ix_content_jobs_brand_profile_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_content_jobs_created_by");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_content_jobs_page_id");

                    b.HasIndex("PlatformCode")
                        .HasDatabaseName("ix_content_jobs_platform_code");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_content_jobs_site_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_content_jobs_tenant_id_created_at");

                    b.ToTable("content_jobs", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.ContentVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Angle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("angle");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("CharCount")
                        .HasColumnType("integer")
                        .HasColumnName("char_count");

                    b.Property<string>("Cta")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cta");

                    b.PrimitiveCollection<List<string>>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("hashtags");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("VariantIndex")
                        .HasColumnType("integer")
                        .HasColumnName("variant_index");

                    b.HasKey("Id")
                        .HasName("pk_content_variants");

                    b.HasIndex("JobId", "VariantIndex")
                        .HasDatabaseName("ix_content_variants_job_id_variant_index");

                    b.ToTable("content_variants", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.PlatformProfile", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("GuidanceTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guidance_tr");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxChars")
                        .HasColumnType("integer")
                        .HasColumnName("max_chars");

                    b.Property<int>("MaxHashtags")
                        .HasColumnType("integer")
                        .HasColumnName("max_hashtags");

                    b.Property<int>("RecommendedChars")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_chars");

                    b.Property<bool>("SupportsLinks")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_links");

                    b.HasKey("Code")
                        .HasName("pk_platform_profiles");

                    b.ToTable("platform_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "instagram",
                            DisplayName = "Instagram",
                            GuidanceTr = "Ilk satir kancadir; link biyoya alinir. Gorsel odakli, 3-5 anlamli hashtag yeterli. Emoji dengeli kullanilir.",
                            IsActive = true,
                            MaxChars = 2200,
                            MaxHashtags = 30,
                            RecommendedChars = 150,
                            SupportsLinks = false
                        },
                        new
                        {
                            Code = "facebook",
                            DisplayName = "Facebook",
                            GuidanceTr = "Kisa metin + tek net CTA en iyi performansi verir. Link onizlemesi otomatik gelir, URL'i metinden cikarabilirsin. Hashtag az kullanilir.",
                            IsActive = true,
                            MaxChars = 63206,
                            MaxHashtags = 3,
                            RecommendedChars = 120,
                            SupportsLinks = true
                        },
                        new
                        {
                            Code = "x",
                            DisplayName = "X",
                            GuidanceTr = "Link iceren gonderilerde erisim duser; linki ilk yanita almayi oner. En fazla 1-2 hashtag. Net, iddiali tek cumle.",
                            IsActive = true,
                            MaxChars = 280,
                            MaxHashtags = 2,
                            RecommendedChars = 240,
                            SupportsLinks = true
                        },
                        new
                        {
                            Code = "linkedin",
                            DisplayName = "LinkedIn",
                            GuidanceTr = "Profesyonel ton, degerli icgoru ile basla. Ilk 2 satir 'devamini gor' oncesi gorunur. 3-5 sektorel hashtag. Emoji az.",
                            IsActive = true,
                            MaxChars = 3000,
                            MaxHashtags = 5,
                            RecommendedChars = 1500,
                            SupportsLinks = true
                        });
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.Crawl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryScores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("category_scores");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IssueCounts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issue_counts");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<int>("PagesCrawled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pages_crawled");

                    b.Property<int>("PagesDiscovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pages_discovered");

                    b.Property<string>("ScoringSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scoring_snapshot");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_crawls");

                    b.HasIndex("SiteId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_crawls_site_id_created_at");

                    b.ToTable("crawls", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("CrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_id");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.PrimitiveCollection<List<string>>("H1Texts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("h1texts");

                    b.Property<int>("H2Count")
                        .HasColumnType("integer")
                        .HasColumnName("h2count");

                    b.Property<int?>("HtmlSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("html_size_bytes");

                    b.Property<int>("ImagesNoAlt")
                        .HasColumnType("integer")
                        .HasColumnName("images_no_alt");

                    b.Property<int>("ImagesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("images_total");

                    b.Property<int>("InlinkCount")
                        .HasColumnType("integer")
                        .HasColumnName("inlink_count");

                    b.Property<string>("Lang")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lang");

                    b.Property<string>("MainText")
                        .HasColumnType("text")
                        .HasColumnName("main_text");

                    b.Property<int?>("MetaDescLength")
                        .HasColumnType("integer")
                        .HasColumnName("meta_desc_length");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("meta_description");

                    b.Property<string>("OgData")
                        .HasColumnType("jsonb")
                        .HasColumnName("og_data");

                    b.Property<int>("OutlinkExternal")
                        .HasColumnType("integer")
                        .HasColumnName("outlink_external");

                    b.Property<int>("OutlinkInternal")
                        .HasColumnType("integer")
                        .HasColumnName("outlink_internal");

                    b.Property<string>("RedirectTo")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("redirect_to");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("RobotsMeta")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("robots_meta");

                    b.PrimitiveCollection<List<string>>("SchemaTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("schema_types");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<int?>("TitleLength")
                        .HasColumnType("integer")
                        .HasColumnName("title_length");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<byte[]>("UrlHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("url_hash");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("CrawlId", "ContentHash")
                        .HasDatabaseName("ix_pages_crawl_id_content_hash");

                    b.HasIndex("CrawlId", "StatusCode")
                        .HasDatabaseName("ix_pages_crawl_id_status_code");

                    b.HasIndex("CrawlId", "UrlHash")
                        .IsUnique()
                        .HasDatabaseName("ix_pages_crawl_id_url_hash");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.PageLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnchorText")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("anchor_text");

                    b.Property<Guid>("CrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_id");

                    b.Property<Guid>("FromPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_page_id");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<bool>("IsNofollow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nofollow");

                    b.Property<Guid?>("ToPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_page_id");

                    b.Property<string>("ToUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("to_url");

                    b.HasKey("Id")
                        .HasName("pk_page_links");

                    b.HasIndex("FromPageId")
                        .HasDatabaseName("ix_page_links_from_page_id");

                    b.HasIndex("ToPageId")
                        .HasDatabaseName("ix_page_links_to_page_id");

                    b.HasIndex("CrawlId", "FromPageId")
                        .HasDatabaseName("ix_page_links_crawl_id_from_page_id");

                    b.HasIndex("CrawlId", "ToPageId")
                        .HasDatabaseName("ix_page_links_crawl_id_to_page_id");

                    b.ToTable("page_links", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Performance.Vital", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Cls")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cls");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_id");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device");

                    b.Property<int?>("FcpMs")
                        .HasColumnType("integer")
                        .HasColumnName("fcp_ms");

                    b.Property<int?>("InpMs")
                        .HasColumnType("integer")
                        .HasColumnName("inp_ms");

                    b.Property<int?>("LcpMs")
                        .HasColumnType("integer")
                        .HasColumnName("lcp_ms");

                    b.Property<int?>("PerfScore")
                        .HasColumnType("integer")
                        .HasColumnName("perf_score");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<int?>("TtfbMs")
                        .HasColumnType("integer")
                        .HasColumnName("ttfb_ms");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_vitals");

                    b.HasIndex("CrawlId")
                        .HasDatabaseName("ix_vitals_crawl_id");

                    b.HasIndex("SiteId", "Url", "CollectedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_vitals_site_id_url_collected_at");

                    b.ToTable("vitals", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Reporting.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompareCrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("compare_crawl_id");

                    b.Property<Guid>("CrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_id");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("CrawlId")
                        .HasDatabaseName("ix_reports_crawl_id");

                    b.HasIndex("SiteId", "CrawlId")
                        .HasDatabaseName("ix_reports_site_id_crawl_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Rules.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("FirstSeenCrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_seen_crawl_id");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<Guid?>("ResolvedCrawlId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_crawl_id");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_issues_page_id");

                    b.HasIndex("RuleCode")
                        .HasDatabaseName("ix_issues_rule_code");

                    b.HasIndex("CrawlId", "Severity")
                        .HasDatabaseName("ix_issues_crawl_id_severity");

                    b.HasIndex("SiteId", "RuleCode", "Status")
                        .HasDatabaseName("ix_issues_site_id_rule_code_status");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Rules.IssueIgnore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_code");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("UrlPattern")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url_pattern");

                    b.HasKey("Id")
                        .HasName("pk_issue_ignores");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_issue_ignores_created_by");

                    b.HasIndex("SiteId", "RuleCode")
                        .HasDatabaseName("ix_issue_ignores_site_id_rule_code");

                    b.ToTable("issue_ignores", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Rules.Rule", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("DescriptionTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_tr");

                    b.Property<string>("DocUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("doc_url");

                    b.Property<string>("HowToFixTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("how_to_fix_tr");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("TitleTr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_tr");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Code")
                        .HasName("pk_rules");

                    b.ToTable("rules", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "HTTP_STATUS",
                            Category = "indexability",
                            DescriptionTr = "Sayfa 4xx/5xx durum kodu donuyor ve dizine eklenemez.",
                            HowToFixTr = "Sunucu/yonlendirme yapilandirmasini duzelt, kalici 200 don.",
                            IsActive = true,
                            Severity = "critical",
                            TitleTr = "Sayfa 2xx donmuyor",
                            Weight = 10
                        },
                        new
                        {
                            Code = "META_TITLE_MISSING",
                            Category = "meta",
                            DescriptionTr = "Sayfada <title> etiketi bulunmuyor.",
                            HowToFixTr = "Her sayfaya 30-60 karakter, anahtar kelime iceren benzersiz bir title ekle.",
                            IsActive = true,
                            Severity = "critical",
                            TitleTr = "Title etiketi yok",
                            Weight = 9
                        },
                        new
                        {
                            Code = "META_TITLE_LENGTH",
                            Category = "meta",
                            DescriptionTr = "Title 30 karakterden kisa veya 60 karakterden uzun.",
                            HowToFixTr = "Title'i 30-60 karakter araligina getir.",
                            IsActive = true,
                            Severity = "medium",
                            TitleTr = "Title uzunlugu ideal degil",
                            Weight = 5
                        },
                        new
                        {
                            Code = "META_DESCRIPTION_MISSING",
                            Category = "meta",
                            DescriptionTr = "Sayfada meta description yok; SERP snippet'i kontrolsuz.",
                            HowToFixTr = "70-160 karakter, tiklama tesvik eden bir meta description yaz.",
                            IsActive = true,
                            Severity = "high",
                            TitleTr = "Meta description yok",
                            Weight = 6
                        },
                        new
                        {
                            Code = "META_DESCRIPTION_LENGTH",
                            Category = "meta",
                            DescriptionTr = "Meta description 70 karakterden kisa veya 160 karakterden uzun.",
                            HowToFixTr = "Uzunlugu 70-160 karakter araligina cek.",
                            IsActive = true,
                            Severity = "low",
                            TitleTr = "Meta description uzunlugu ideal degil",
                            Weight = 3
                        },
                        new
                        {
                            Code = "H1_MISSING",
                            Category = "content",
                            DescriptionTr = "Sayfada H1 basligi bulunmuyor.",
                            HowToFixTr = "Sayfa basina tek ve aciklayici bir H1 ekle.",
                            IsActive = true,
                            Severity = "high",
                            TitleTr = "H1 yok",
                            Weight = 6
                        },
                        new
                        {
                            Code = "H1_MULTIPLE",
                            Category = "content",
                            DescriptionTr = "Sayfada birden cok H1 var.",
                            HowToFixTr = "Tek H1 birak, digerlerini H2/H3 yap.",
                            IsActive = true,
                            Severity = "medium",
                            TitleTr = "Birden fazla H1",
                            Weight = 4
                        },
                        new
                        {
                            Code = "CANONICAL_MISSING",
                            Category = "indexability",
                            DescriptionTr = "rel=canonical etiketi tanimli degil.",
                            HowToFixTr = "Kendine referans veren bir canonical URL ekle.",
                            IsActive = true,
                            Severity = "low",
                            TitleTr = "Canonical yok",
                            Weight = 3
                        },
                        new
                        {
                            Code = "THIN_CONTENT",
                            Category = "content",
                            DescriptionTr = "Sayfa metni 300 kelimenin altinda.",
                            HowToFixTr = "Icerigi ozgun ve kullaniciya deger katacak sekilde genislet.",
                            IsActive = true,
                            Severity = "medium",
                            TitleTr = "Zayif icerik",
                            Weight = 5
                        },
                        new
                        {
                            Code = "DUPLICATE_CONTENT",
                            Category = "content",
                            DescriptionTr = "Ayni content_hash birden fazla sayfada goruluyor.",
                            HowToFixTr = "Icerigi farklilastir veya canonical ile asil sayfayi isaret et.",
                            IsActive = true,
                            Severity = "high",
                            TitleTr = "Yinelenen icerik",
                            Weight = 7
                        },
                        new
                        {
                            Code = "NOINDEX_DETECTED",
                            Category = "indexability",
                            DescriptionTr = "robots meta veya X-Robots-Tag noindex iceriyor.",
                            HowToFixTr = "Dizine girmesi gereken sayfalarda noindex'i kaldir.",
                            IsActive = true,
                            Severity = "critical",
                            TitleTr = "noindex etiketi",
                            Weight = 9
                        },
                        new
                        {
                            Code = "BROKEN_INTERNAL_LINK",
                            Category = "links",
                            DescriptionTr = "Ic link 4xx/5xx donen bir sayfaya gidiyor.",
                            HowToFixTr = "Hedefi guncelle veya linki kaldir.",
                            IsActive = true,
                            Severity = "high",
                            TitleTr = "Kirik ic link",
                            Weight = 6
                        },
                        new
                        {
                            Code = "IMAGE_ALT_MISSING",
                            Category = "images",
                            DescriptionTr = "Bir veya daha fazla <img> alt niteligi tasimiyor.",
                            HowToFixTr = "Anlamli gorsellere aciklayici alt metni ekle.",
                            IsActive = true,
                            Severity = "low",
                            TitleTr = "Alt metni eksik gorseller",
                            Weight = 3
                        },
                        new
                        {
                            Code = "SLOW_TTFB",
                            Category = "performance",
                            DescriptionTr = "Ilk bayt suresi 800 ms'nin uzerinde.",
                            HowToFixTr = "Sunucu yanit suresini, cache ve CDN kullanimini iyilestir.",
                            IsActive = true,
                            Severity = "medium",
                            TitleTr = "Yavas TTFB",
                            Weight = 5
                        },
                        new
                        {
                            Code = "POOR_LCP",
                            Category = "performance",
                            DescriptionTr = "Largest Contentful Paint 2.5 sn'nin uzerinde.",
                            HowToFixTr = "Kritik gorselleri onceliklendir, render-blocking kaynaklari azalt.",
                            IsActive = true,
                            Severity = "high",
                            TitleTr = "Kotu LCP",
                            Weight = 7
                        },
                        new
                        {
                            Code = "STRUCTURED_DATA_MISSING",
                            Category = "structured_data",
                            DescriptionTr = "Sayfada schema.org isaretlemesi bulunamadi.",
                            HowToFixTr = "Uygun schema tipini (Article, Product, FAQ...) JSON-LD olarak ekle.",
                            IsActive = true,
                            Severity = "low",
                            TitleTr = "Yapisal veri yok",
                            Weight = 3
                        },
                        new
                        {
                            Code = "HREFLANG_INVALID",
                            Category = "i18n",
                            DescriptionTr = "hreflang deger(ler)i gecersiz veya karsilikli degil.",
                            HowToFixTr = "Dil-bolge kodlarini duzelt ve karsilikli hreflang tanimla.",
                            IsActive = true,
                            Severity = "medium",
                            TitleTr = "Gecersiz hreflang",
                            Weight = 4
                        });
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DefaultBrandProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_brand_profile_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleCron")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schedule_cron");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verification_method");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("verification_token");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_sites_tenant_id_is_active");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.System.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_id");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_tenant_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AiTokenQuota")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_token_quota");

                    b.Property<long>("AiTokensUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("ai_tokens_used");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PageQuota")
                        .HasColumnType("integer")
                        .HasColumnName("page_quota");

                    b.Property<int>("PagesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pages_used");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset?>("QuotaResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quota_reset_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.BrandProfile", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brand_profiles_sites_site_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_profiles_tenants_tenant_id");

                    b.Navigation("Site");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.ContentJob", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Content.BrandProfile", "BrandProfile")
                        .WithMany()
                        .HasForeignKey("BrandProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_content_jobs_brand_profiles_brand_profile_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_content_jobs_users_created_by");

                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_content_jobs_pages_page_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Content.PlatformProfile", "Platform")
                        .WithMany("ContentJobs")
                        .HasForeignKey("PlatformCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_content_jobs_platform_profiles_platform_code");

                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_content_jobs_sites_site_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_jobs_tenants_tenant_id");

                    b.Navigation("BrandProfile");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Page");

                    b.Navigation("Platform");

                    b.Navigation("Site");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.ContentVariant", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Content.ContentJob", "Job")
                        .WithMany("Variants")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_variants_content_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.Crawl", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany("Crawls")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crawls_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.Page", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Crawl", "Crawl")
                        .WithMany("Pages")
                        .HasForeignKey("CrawlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pages_crawls_crawl_id");

                    b.Navigation("Crawl");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.PageLink", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Page", "FromPage")
                        .WithMany("OutLinks")
                        .HasForeignKey("FromPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_links_pages_from_page_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Page", "ToPage")
                        .WithMany()
                        .HasForeignKey("ToPageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_page_links_pages_to_page_id");

                    b.Navigation("FromPage");

                    b.Navigation("ToPage");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Performance.Vital", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Crawl", "Crawl")
                        .WithMany()
                        .HasForeignKey("CrawlId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vitals_crawls_crawl_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vitals_sites_site_id");

                    b.Navigation("Crawl");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Reporting.Report", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Crawl", "Crawl")
                        .WithMany()
                        .HasForeignKey("CrawlId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reports_crawls_crawl_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_sites_site_id");

                    b.Navigation("Crawl");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Rules.Issue", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Crawl", "Crawl")
                        .WithMany("Issues")
                        .HasForeignKey("CrawlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_crawls_crawl_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Crawling.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_issues_pages_page_id");

                    b.HasOne("SeoCopilot.Domain.Entities.Rules.Rule", "Rule")
                        .WithMany("Issues")
                        .HasForeignKey("RuleCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_issues_rules_rule_code");

                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_issues_sites_site_id");

                    b.OwnsOne("SeoCopilot.Domain.Entities.Json.IssueEvidence", "Evidence", b1 =>
                        {
                            b1.Property<long>("IssueId");

                            b1.Property<string>("Expected");

                            b1.Property<string>("Found");

                            b1.Property<int?>("Length");

                            b1.PrimitiveCollection<string>("SampleUrls")
                                .IsRequired();

                            b1.HasKey("IssueId");

                            b1.ToTable("issues");

                            b1
                                .ToJson("evidence")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IssueId")
                                .HasConstraintName("fk_issues_issues_id");
                        });

                    b.Navigation("Crawl");

                    b.Navigation("Evidence")
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Rule");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Rules.IssueIgnore", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_issue_ignores_users_created_by");

                    b.HasOne("SeoCopilot.Domain.Entities.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_ignores_sites_site_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Sites.Site", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sites_tenants_tenant_id");

                    b.OwnsOne("SeoCopilot.Domain.Entities.Json.CrawlSettings", "CrawlSettings", b1 =>
                        {
                            b1.Property<Guid>("SiteId");

                            b1.Property<int>("Concurrency");

                            b1.Property<int>("DelayMs");

                            b1.PrimitiveCollection<string>("ExcludePatterns")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("IncludePatterns")
                                .IsRequired();

                            b1.Property<int>("MaxDepth");

                            b1.Property<int>("MaxPages");

                            b1.Property<bool>("RenderJs");

                            b1.HasKey("SiteId");

                            b1.ToTable("sites");

                            b1
                                .ToJson("crawl_settings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SiteId")
                                .HasConstraintName("fk_sites_sites_id");
                        });

                    b.Navigation("CrawlSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.RefreshToken", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.User", b =>
                {
                    b.HasOne("SeoCopilot.Domain.Entities.Tenancy.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.ContentJob", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Content.PlatformProfile", b =>
                {
                    b.Navigation("ContentJobs");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.Crawl", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Crawling.Page", b =>
                {
                    b.Navigation("OutLinks");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Rules.Rule", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Sites.Site", b =>
                {
                    b.Navigation("Crawls");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SeoCopilot.Domain.Entities.Tenancy.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
